name: Deploy Databricks Job

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run the workflow manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Reset Databricks Job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }} # Store your host as a secret
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          run: databricks jobs create --json-file case_studies/StorySpark/src/book_inventory/sync_book_inventory_job.json

